require('dotenv').config();
const fs = require('fs');
const { getTopGameFiProjects, getNewGameFiContracts } = require('./radar');
const { getGameFiNFTTrends, getWeeklyDigest } = require('./assets');
const { getHackathonAlerts, getGrantAlerts } = require('./alerts');
const path = require('path');
const https = require('https');

const FREE_MODELS = [
  'openrouter/auto',
  'google/gemma-4-31b-it:free',
  'google/gemma-4-26b-a4b-it:free',
  'nvidia/nemotron-3-super-120b-a12b:free',
  'poolside/laguna-m.1:free'
];

function requestModel(model, prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model,
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }]
    });
    const req = https.request({
      hostname: 'openrouter.ai',
      path: '/api/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + process.env.OPENAI_API_KEY,
        'HTTP-Referer': 'https://github.com/alinasisi/base-gamefi-radar',
        'X-Title': 'Base GameFi Radar'
      }
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          if (json.error || !json.choices || !json.choices[0]) {
            reject(new Error(json.error?.message || 'No response'));
            return;
          }
          resolve(json.choices[0].message.content);
        } catch(e) { reject(e); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

async function aiRequest(prompt) {
  for (const model of FREE_MODELS) {
    try {
      console.log('Trying: ' + model);
      const result = await requestModel(model, prompt);
      console.log('Success: ' + model);
      return result;
    } catch(e) {
      console.log('Failed (' + model + '): ' + e.message);
    }
  }
  return '*AI analysis unavailable*';
}

async function generateReport() {
  const date = new Date().toISOString().split('T')[0];
  const day = new Date().getDay();
  console.log('Generating GameFi radar for ' + date + '...');

  const [topGames, newContracts, nftTrends, hackathons, grants] = await Promise.all([
    getTopGameFiProjects(),
    getNewGameFiContracts(),
    getGameFiNFTTrends(),
    getHackathonAlerts(),
    getGrantAlerts()
  ]);

  const analysis = await aiRequest(
    'You are a GameFi analyst focused on Base blockchain. Write a sharp daily insight (150-200 words) for ' + date + ' covering: 1. One emerging trend in Base GameFi today 2. Which game mechanic is gaining traction on Base 3. One actionable opportunity for a GameFi builder. Be specific, no fluff. Format as markdown.'
  );

  const weeklySection = day === 0 ? await getWeeklyDigest(analysis) : '';

  const report = [
    '# GameFi Radar — ' + date,
    '',
    '## Ecosystem Analysis',
    analysis,
    '',
    '## Top GameFi Projects on Base',
    topGames,
    '',
    '## NFT Asset Trends',
    nftTrends,
    '',
    '## Hackathons',
    hackathons,
    '',
    '## Grants',
    grants,
    '',
    weeklySection,
    '',
    '*Auto-generated by base-gamefi-radar*'
  ].join('\n');

  const dir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, date + '.md'), report);
  console.log('Report saved: reports/' + date + '.md');

  const files = fs.readdirSync(dir)
    .filter(f => f.endsWith('.md') && f !== 'README.md')
    .sort().reverse()
    .map(f => '- [' + f.replace('.md','') + '](' + f + ')');

  fs.writeFileSync(path.join(dir, 'README.md'),
    '# GameFi Reports\n\nDaily Base GameFi intelligence.\n\n' + files.join('\n') + '\n'
  );

  console.log('Done!');
}

generateReport().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
